config/routes.rb
Rails.application.routes.draw do
  resources :evaluateds
  resources :evaluator_instruments
  resources :instruments
  resources :evaluators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/evaluator.rb
class Evaluator < ApplicationRecord
  belongs_to :user
  has_many :evaluator_instruments

  validates :name, presence: true
  validates :cpf, presence: true
  validates :email, presence: true
  validates :date_of_birth, presence: true
end

app/controllers/evaluators_controller.rb
class EvaluatorsController < ApplicationController
  before_action :set_evaluator, only: %i[ show edit update destroy ]

  # GET /evaluators or /evaluators.json
  def index
    @evaluators = Evaluator.all
  end

  # GET /evaluators/1 or /evaluators/1.json
  def show
  end

  # GET /evaluators/new
  def new
    @evaluator = Evaluator.new
  end

  # GET /evaluators/1/edit
  def edit
  end

  # POST /evaluators or /evaluators.json
  def create
    @evaluator = Evaluator.new(evaluator_params)

    respond_to do |format|
      if @evaluator.save
        format.html { redirect_to evaluator_url(@evaluator), notice: "Evaluator was successfully created." }
        format.json { render :show, status: :created, location: @evaluator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluators/1 or /evaluators/1.json
  def update
    respond_to do |format|
      if @evaluator.update(evaluator_params)
        format.html { redirect_to evaluator_url(@evaluator), notice: "Evaluator was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluators/1 or /evaluators/1.json
  def destroy
    @evaluator.destroy!

    respond_to do |format|
      format.html { redirect_to evaluators_url, notice: "Evaluator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluator
      @evaluator = Evaluator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluator_params
      params.require(:evaluator).permit(:user_id, :name, :cpf, :email, :date_of_birth)
    end
end

app/helpers/evaluators_helper.rb
module EvaluatorsHelper
end

app/views/evaluators/_evaluator.html.erb
<div id="<%= dom_id evaluator %>">
  <p>
    <strong>User:</strong>
    <%= evaluator.user_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= evaluator.name %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= evaluator.cpf %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= evaluator.email %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= evaluator.date_of_birth %>
  </p>

</div>

app/views/evaluators/_form.html.erb
<%= form_with(model: evaluator) do |form| %>
  <% if evaluator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(evaluator.errors.count, "error") %> prohibited this evaluator from being saved:</h2>

      <ul>
        <% evaluator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluators/edit.html.erb
<h1>Editing evaluator</h1>

<%= render "form", evaluator: @evaluator %>

<br>

<div>
  <%= link_to "Show this evaluator", @evaluator %> |
  <%= link_to "Back to evaluators", evaluators_path %>
</div>

app/views/evaluators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evaluators</h1>

<div id="evaluators">
  <% @evaluators.each do |evaluator| %>
    <%= render evaluator %>
    <p>
      <%= link_to "Show this evaluator", evaluator %>
    </p>
  <% end %>
</div>

<%= link_to "New evaluator", new_evaluator_path %>

app/views/evaluators/new.html.erb
<h1>New evaluator</h1>

<%= render "form", evaluator: @evaluator %>

<br>

<div>
  <%= link_to "Back to evaluators", evaluators_path %>
</div>

app/views/evaluators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluator %>

<div>
  <%= link_to "Edit this evaluator", edit_evaluator_path(@evaluator) %> |
  <%= link_to "Back to evaluators", evaluators_path %>

  <%= button_to "Destroy this evaluator", @evaluator, method: :delete %>
</div>