config/routes.rb
Rails.application.routes.draw do
  resources :evaluateds
  resources :evaluator_instruments
  resources :instruments
  resources :evaluators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/evaluated.rb
class Evaluated < ApplicationRecord
  validates :name, presence: true
  validates :cpf, presence: true
  validates :email, presence: true
  validates :date_of_birth, presence: true
end

app/controllers/evaluateds_controller.rb
class EvaluatedsController < ApplicationController
  before_action :set_evaluated, only: %i[ show edit update destroy ]

  # GET /evaluateds or /evaluateds.json
  def index
    @evaluateds = Evaluated.all
  end

  # GET /evaluateds/1 or /evaluateds/1.json
  def show
  end

  # GET /evaluateds/new
  def new
    @evaluated = Evaluated.new
  end

  # GET /evaluateds/1/edit
  def edit
  end

  # POST /evaluateds or /evaluateds.json
  def create
    @evaluated = Evaluated.new(evaluated_params)

    respond_to do |format|
      if @evaluated.save
        format.html { redirect_to evaluated_url(@evaluated), notice: "Evaluated was successfully created." }
        format.json { render :show, status: :created, location: @evaluated }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluated.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluateds/1 or /evaluateds/1.json
  def update
    respond_to do |format|
      if @evaluated.update(evaluated_params)
        format.html { redirect_to evaluated_url(@evaluated), notice: "Evaluated was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluated }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluated.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluateds/1 or /evaluateds/1.json
  def destroy
    @evaluated.destroy!

    respond_to do |format|
      format.html { redirect_to evaluateds_url, notice: "Evaluated was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluated
      @evaluated = Evaluated.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluated_params
      params.require(:evaluated).permit(:name, :email, :cpf, :date_of_birth)
    end
end

app/helpers/evaluateds_helper.rb
module EvaluatedsHelper
end

app/views/evaluateds/_evaluated.html.erb
<div id="<%= dom_id evaluated %>">
  <p>
    <strong>Name:</strong>
    <%= evaluated.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= evaluated.email %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= evaluated.cpf %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= evaluated.date_of_birth %>
  </p>

</div>

app/views/evaluateds/_form.html.erb
<%= form_with(model: evaluated) do |form| %>
  <% if evaluated.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(evaluated.errors.count, "error") %> prohibited this evaluated from being saved:</h2>

      <ul>
        <% evaluated.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluateds/edit.html.erb
<h1>Editing evaluated</h1>

<%= render "form", evaluated: @evaluated %>

<br>

<div>
  <%= link_to "Show this evaluated", @evaluated %> |
  <%= link_to "Back to evaluateds", evaluateds_path %>
</div>

app/views/evaluateds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evaluateds</h1>

<div id="evaluateds">
  <% @evaluateds.each do |evaluated| %>
    <%= render evaluated %>
    <p>
      <%= link_to "Show this evaluated", evaluated %>
    </p>
  <% end %>
</div>

<%= link_to "New evaluated", new_evaluated_path %>

app/views/evaluateds/new.html.erb
<h1>New evaluated</h1>

<%= render "form", evaluated: @evaluated %>

<br>

<div>
  <%= link_to "Back to evaluateds", evaluateds_path %>
</div>

app/views/evaluateds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluated %>

<div>
  <%= link_to "Edit this evaluated", edit_evaluated_path(@evaluated) %> |
  <%= link_to "Back to evaluateds", evaluateds_path %>

  <%= button_to "Destroy this evaluated", @evaluated, method: :delete %>
</div>