config/routes.rb
Rails.application.routes.draw do
  resources :evaluateds
  resources :evaluator_instruments
  resources :instruments
  resources :evaluators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/evaluator_instrument.rb
class EvaluatorInstrument < ApplicationRecord
  belongs_to :evaluator
  belongs_to :instrument
end

app/controllers/evaluator_instruments_controller.rb
class EvaluatorInstrumentsController < ApplicationController
  before_action :set_evaluator_instrument, only: %i[ show edit update destroy ]

  # GET /evaluator_instruments or /evaluator_instruments.json
  def index
    @evaluator_instruments = EvaluatorInstrument.all
  end

  # GET /evaluator_instruments/1 or /evaluator_instruments/1.json
  def show
  end

  # GET /evaluator_instruments/new
  def new
    @evaluator_instrument = EvaluatorInstrument.new
  end

  # GET /evaluator_instruments/1/edit
  def edit
  end

  # POST /evaluator_instruments or /evaluator_instruments.json
  def create
    @evaluator_instrument = EvaluatorInstrument.new(evaluator_instrument_params)

    respond_to do |format|
      if @evaluator_instrument.save
        format.html { redirect_to evaluator_instrument_url(@evaluator_instrument), notice: "Evaluator instrument was successfully created." }
        format.json { render :show, status: :created, location: @evaluator_instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluator_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluator_instruments/1 or /evaluator_instruments/1.json
  def update
    respond_to do |format|
      if @evaluator_instrument.update(evaluator_instrument_params)
        format.html { redirect_to evaluator_instrument_url(@evaluator_instrument), notice: "Evaluator instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluator_instrument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluator_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluator_instruments/1 or /evaluator_instruments/1.json
  def destroy
    @evaluator_instrument.destroy!

    respond_to do |format|
      format.html { redirect_to evaluator_instruments_url, notice: "Evaluator instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluator_instrument
      @evaluator_instrument = EvaluatorInstrument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluator_instrument_params
      params.require(:evaluator_instrument).permit(:evaluator_id, :instrument_id, :date)
    end
end

app/helpers/evaluator_instruments_helper.rb
module EvaluatorInstrumentsHelper
end

app/views/evaluator_instruments/_evaluator_instrument.html.erb
<div id="<%= dom_id evaluator_instrument %>">
  <p>
    <strong>Evaluator:</strong>
    <%= evaluator_instrument.evaluator_id %>
  </p>

  <p>
    <strong>Instrument:</strong>
    <%= evaluator_instrument.instrument_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= evaluator_instrument.date %>
  </p>

</div>

app/views/evaluator_instruments/_form.html.erb
<%= form_with(model: evaluator_instrument) do |form| %>
  <% if evaluator_instrument.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(evaluator_instrument.errors.count, "error") %> prohibited this evaluator_instrument from being saved:</h2>

      <ul>
        <% evaluator_instrument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :evaluator_id, style: "display: block" %>
    <%= form.text_field :evaluator_id %>
  </div>

  <div>
    <%= form.label :instrument_id, style: "display: block" %>
    <%= form.text_field :instrument_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluator_instruments/edit.html.erb
<h1>Editing evaluator instrument</h1>

<%= render "form", evaluator_instrument: @evaluator_instrument %>

<br>

<div>
  <%= link_to "Show this evaluator instrument", @evaluator_instrument %> |
  <%= link_to "Back to evaluator instruments", evaluator_instruments_path %>
</div>

app/views/evaluator_instruments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evaluator instruments</h1>

<div id="evaluator_instruments">
  <% @evaluator_instruments.each do |evaluator_instrument| %>
    <%= render evaluator_instrument %>
    <p>
      <%= link_to "Show this evaluator instrument", evaluator_instrument %>
    </p>
  <% end %>
</div>

<%= link_to "New evaluator instrument", new_evaluator_instrument_path %>

app/views/evaluator_instruments/new.html.erb
<h1>New evaluator instrument</h1>

<%= render "form", evaluator_instrument: @evaluator_instrument %>

<br>

<div>
  <%= link_to "Back to evaluator instruments", evaluator_instruments_path %>
</div>

app/views/evaluator_instruments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluator_instrument %>

<div>
  <%= link_to "Edit this evaluator instrument", edit_evaluator_instrument_path(@evaluator_instrument) %> |
  <%= link_to "Back to evaluator instruments", evaluator_instruments_path %>

  <%= button_to "Destroy this evaluator instrument", @evaluator_instrument, method: :delete %>
</div>