config/routes.rb
Rails.application.routes.draw do
  resources :evaluateds
  resources :evaluator_instruments
  resources :instruments
  resources :evaluators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :evaluator_instruments

  validates :question_one, presence: true
  validates :question_two, presence: true
  validates :question_tree, presence: true
  validates :question_four, presence: true
  validates :question_five, presence: true
  validates :title, presence: true
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[ show edit update destroy ]

  # GET /instruments or /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1 or /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments or /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument was successfully created." }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1 or /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1 or /instruments/1.json
  def destroy
    @instrument.destroy!

    respond_to do |format|
      format.html { redirect_to instruments_url, notice: "Instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instrument_params
      params.require(:instrument).permit(:question_one, :question_two, :question_tree, :question_four, :question_five)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<%= form_with(model: instrument) do |form| %>
  <% if instrument.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
        <% instrument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question_one, style: "display: block" %>
    <%= form.text_area :question_one %>
  </div>

  <div>
    <%= form.label :question_two, style: "display: block" %>
    <%= form.text_area :question_two %>
  </div>

  <div>
    <%= form.label :question_tree, style: "display: block" %>
    <%= form.text_area :question_tree %>
  </div>

  <div>
    <%= form.label :question_four, style: "display: block" %>
    <%= form.text_area :question_four %>
  </div>

  <div>
    <%= form.label :question_five, style: "display: block" %>
    <%= form.text_area :question_five %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instruments/_instrument.html.erb
<div id="<%= dom_id instrument %>">
  <p>
    <strong>Question one:</strong>
    <%= instrument.question_one %>
  </p>

  <p>
    <strong>Question two:</strong>
    <%= instrument.question_two %>
  </p>

  <p>
    <strong>Question tree:</strong>
    <%= instrument.question_tree %>
  </p>

  <p>
    <strong>Question four:</strong>
    <%= instrument.question_four %>
  </p>

  <p>
    <strong>Question five:</strong>
    <%= instrument.question_five %>
  </p>

</div>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render "form", instrument: @instrument %>

<br>

<div>
  <%= link_to "Show this instrument", @instrument %> |
  <%= link_to "Back to instruments", instruments_path %>
</div>

app/views/instruments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Instruments</h1>

<div id="instruments">
  <% @instruments.each do |instrument| %>
    <%= render instrument %>
    <p>
      <%= link_to "Show this instrument", instrument %>
    </p>
  <% end %>
</div>

<%= link_to "New instrument", new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render "form", instrument: @instrument %>

<br>

<div>
  <%= link_to "Back to instruments", instruments_path %>
</div>

app/views/instruments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @instrument %>

<div>
  <%= link_to "Edit this instrument", edit_instrument_path(@instrument) %> |
  <%= link_to "Back to instruments", instruments_path %>

  <%= button_to "Destroy this instrument", @instrument, method: :delete %>
</div>